<a href="https://colab.research.google.com/github/raqueeb/pytorch-bangla/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## প্র্যাকটিস নোট

নিচে ভিডিওর অংশটা পাবেন

In [1]:
import torch

In [2]:
x = torch.Tensor([3])
y = torch.Tensor([17])  

In [3]:
x.requires_grad_()

tensor([3.], requires_grad=True)

In [4]:

y.requires_grad_()


tensor([17.], requires_grad=True)

In [5]:
print(x)

tensor([3.], requires_grad=True)


In [6]:
loss = x**2 * y + y
loss

tensor([170.], grad_fn=<AddBackward0>)

In [7]:
loss.backward(create_graph=True, retain_graph=True)

In [8]:
xx = x.grad

In [9]:
xx

tensor([102.], grad_fn=<CopyBackwards>)

In [10]:
xx.requires_grad_()

tensor([102.], grad_fn=<CopyBackwards>)

In [11]:
result = torch.autograd.grad(xx, y)

In [12]:
result

(tensor([6.]),)

## ভিডিওর অংশ

## টেন্সর অপারেশন এবং গ্র্যাডিয়েন্ট 

In [13]:
import torch

### টেন্সর তৈরি করছি ৩টা 

w, b এর ব্যাপারে অটোগ্র্যাডকে সিগন্যাল দিচ্ছি, সব অপারেশন্সকে মনে রাখবে।

In [14]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

### অংকের কাজ

সাধারণ পাইথনের কাজ

৪ * ৩ + ৫ = ১৭

In [15]:
y =w * x + b 
y

tensor(17., grad_fn=<AddBackward0>)

### ডিরাইভেটিভ হিসেব করি



In [16]:
y.backward()

### গ্র্যাডিয়েন্টগুলো দেখি 

dy/dx: এর কোন ডিরাইভেটিভ নেই।

dy/dw: এর মান কতো হবে? মনে আছে ক্যালকুলাসের কথা?

dy/db: কী হতে পারে?


রেজাল্ট দেখি?

In [17]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)
