In [1]:
import torch
import numpy

In [2]:
numpy.array([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

array([[0.1, 1.2],
       [2.2, 3.1],
       [4.9, 5.2]])

In [3]:
torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [9]:
a = numpy.ones(5)     #From NumPy to Torch
b = torch.from_numpy(a)

print('a:',a)
print('b:',b)

a: [1. 1. 1. 1. 1.]
b: tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [10]:
w = torch.empty(3, 3)
print(w,'\n', w.shape, '\n')

x = torch.randn(3, 3, 7)
print(x,'\n', x.shape, '\n')

y = torch.zeros(3, 3)
print(y,'\n', y.shape, '\n')

z = torch.ones(3, 3)
print(z,'\n', z.shape, '\n')

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 
 torch.Size([3, 3]) 

tensor([[[-0.6692, -0.7776,  1.5694,  0.8352,  1.3476, -0.5720,  0.7283],
         [-1.0007,  0.7241,  1.3452,  0.8588, -0.2995, -1.4560,  1.7915],
         [ 1.9128, -0.2632, -0.8691, -1.4808,  0.3628,  0.7167,  0.4264]],

        [[-0.2009,  0.9550,  0.6067, -0.1201, -0.9100,  0.3047, -1.1209],
         [ 0.2995,  1.7401, -0.0402, -0.1051,  0.2420, -0.7066, -2.5937],
         [-0.7033, -0.1201, -1.8913, -0.9631, -1.3150, -0.1321,  0.0420]],

        [[ 0.8668,  0.8282, -1.4489,  0.6600, -0.5077, -1.3425, -0.9259],
         [ 0.2660, -1.7182, -0.4228,  0.4109,  1.9769,  0.3062, -0.4206],
         [-1.7841, -1.0168,  0.0152, -1.0633,  0.6879,  0.4970,  0.1162]]]) 
 torch.Size([3, 3, 7]) 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 
 torch.Size([3, 3]) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 
 torch.Size([3, 3]) 



In [11]:
x = torch.rand(100,50)
print(x.shape)

y=x.view(20,5,50)
print(y.shape)

z=x.view(-1,5,50)
print(z.shape)

torch.Size([100, 50])
torch.Size([20, 5, 50])
torch.Size([20, 5, 50])


In [4]:
cpu=torch.device("cpu")
gpu=torch.device("cuda:0") # GPU 0# Create tensor with CPU

x=torch.ones(3,3, device=cpu)
print("CPU:",x.device)

x=torch.ones(3,3, device=gpu)
print("GPU:",x.device)

x=torch.ones(3,3).cuda(0)
print("CPU to GPU:",x.device)

x=torch.ones(3,3, device=gpu).cpu()
print("GPU to CPU:",x.device)

CPU: cpu
GPU: cuda:0
CPU to GPU: cuda:0
GPU to CPU: cpu


In [5]:
import time

x=torch.rand(10000,10000)
y=torch.rand(10000,10000)

t = time.time()
z = x@y
t = time.time()-t
print(t)

9.447360038757324


In [6]:
xc = x.cuda(0)
yc = y.cuda(0)

t = time.time()

z = xc@yc
t = time.time()-t

print(t)

0.3421015739440918
